### ISSUE TITLE
dos2unix

### ISSUE THREAD

**Issue by bannsec** [Neo23x0/yarGen#16]
Using unix line returns will be more universal and lead to less confusion when linux folk attempt to run this tool. Either coding in a unix line return compatible editor or adding a hook into git to change the line returns would be beneficial.

https://stackoverflow.com/questions/15223290/fixing-mac-windows-new-lines-with-git-pre-commit-hook

**Comment by Neo23x0** [comment]
That's a legacy issue that my IDE (PyCharm) on OSX hides from my attention. I just changed the line separators to Unix/Linux style. ('\r\n' > '\n')
