### ISSUE TITLE
Error when running yargen

### ISSUE THREAD

**Issue by gbiagomba** [Neo23x0/yarGen#17]
![image](https://user-images.githubusercontent.com/5851606/31188034-ab87c546-a901-11e7-84d1-dd9033040db7.png)

python yarGen.py -c --opcodes -i office -g '/root/Downloads/vivaldi-stable_1.12.955.36-1_i386.deb' 
Traceback (most recent call last):
  File "yarGen.py", line 25, in <module>
    from naiveBayesClassifier import tokenizer
ImportError: No module named naiveBayesClassifier

python3 yarGen.py --update
  File "yarGen.py", line 33
    except Exception, e:
                    ^
SyntaxError: invalid syntax

I am not sure what the issue is, I made sure that the package naiveBayesClassifier was installed

**Comment by Neo23x0** [comment]
The issue is that you're using Python3 and not Python2

**Comment by gbiagomba** [comment]
Actually my default is python2 and i tried python2 first then tried python3...hence why the errors looked a bit different from one another. But the issue appears to be resolved and its working now. Idk what was up but all is well lol
