### ISSUE TITLE
rules coverage

### ISSUE THREAD

**Issue by garanews** [Neo23x0/yarGen#18]
Hello,
do you have in mind something able to compare the different generated  rules in order to show the overall overlap?

**Comment by Neo23x0** [comment]
You mean something like

https://github.com/Neo23x0/yarAnalyzer

**Comment by garanews** [comment]
If for example in some way I was able to cluster these 4 samples:
 
4c1017de62ea4788c7c8058a8f825a2d
43e896ede6fe025ee90f7f27c6d376a4
1fb407a20373f3970f08d3f3c086841d
91a5594343b47462ebd6266a9c40abbe

![image](https://user-images.githubusercontent.com/16938405/41588041-f3e87f54-73b0-11e8-9475-f15b33f02b53.png)


yaraGen will generate a rule for each file (files will not come simultaneously).
So I'm wondering if there is something that can compare the 4 rules and maybe create a superrule that is able to catch the 4 samples, or maybe generate a superrule every time the cluster is updated with new samples.
One rule to rule them all :)

**Comment by Hyperion101010** [comment]
Sir i am an undergrad student in engineering .
I am interesting in writting a new framework for yara rules generation .
I know it is a big task at least for me .Also i don't have that much of a an experience writting code for big frameworks 
Collabrative development is always favoured !
I need to share my idea and get an expertise from you  , will you help ?
