### ISSUE TITLE
Error in getting update for dbs

### ISSUE THREAD

**Issue by darkmonk94** [Neo23x0/yarGen#25]
###############################################################################
Downloading good-strings-part7.db from https://www.bsk-consulting.de/yargen/good-strings-part7.db ...
Error while downloading the database file - check your Internet connection
Alterntive download link: https://drive.google.com/drive/folders/0B2S_IOa0MiOHS0xmekR6VWRhZ28
Download the files and place them into the ./dbs/ folder

The alternative download link for the drive has no content. it says: This folder is in the owner's trash
To view this folder, ask the owner (Florian) to restore it.

**Comment by Neo23x0** [comment]
As I said in my tweet. This is most likely caused by an outdated Python version that does not accept the SSL certificate of our web server. Try to run it with `--debug`. 

I've ported yarGen to Python3 today. You could give this version a try.

**Comment by darkmonk94** [comment]
Actually I wanted to download it from the Alterntive download link: https://drive.google.com/drive/folders/0B2S_IOa0MiOHS0xmekR6VWRhZ28
and place the downloaded files into the ./dbs/ folder.

But https://drive.google.com/drive/folders/0B2S_IOa0MiOHS0xmekR6VWRhZ28 link has no data. so it could be helpful if you can provide another alternative drive link for the same.

**Comment by darkmonk94** [comment]
Surely I am gonna try the Python 3 version right now..

**Comment by zeze-zeze** [comment]
We can also use unverified context to download dbs without verifying SSL certificate.
```
import ssl

# ......

context = ssl._create_unverified_context()
with urllib.request.urlopen(repo_url, context=context) as response, open("./dbs/%s" % filename, 'wb') as out_file:

# ......
```
