### ISSUE TITLE
Error in YARA rules created

### ISSUE THREAD

**Issue by darkmonk94** [Neo23x0/yarGen#26]
Hi I tried to create rule for two malware sample and it gives me error while testing them in Hybird analysis. As I am new to the YARA so could not understand why the error is, tried to read the YARA documentation also but could not understand the error cause. 

Yara rule is pasted in this link :

https://pastebin.com/UTwFdCSF

Can you help to with a error free version of the same rule so that I can learn the errors. Thanks

**Comment by Neo23x0** [comment]
It's caused by unescaped backslashes. 
You always have to post-process these rules. You shouldn't use them as the generator outputs them.
You have to understand what you're doing.

**Comment by Neo23x0** [comment]
I've fixed the bug in https://github.com/Neo23x0/yarGen/releases/tag/0.23.2

**Comment by Neo23x0** [comment]
See the post-processing video tutorial. 
https://medium.com/@cyb3rops/how-to-post-process-yara-rules-generated-by-yargen-121d29322282

**Comment by darkmonk94** [comment]
Thank you.
