### ISSUE TITLE
Import scandir error

### ISSUE THREAD

**Issue by ghost** [Neo23x0/yarGen#28]
After pulling down yarGen and trying to update, the following error occurs:

Traceback (most recent call last):
  File "yarGen.py", line 21, in <module>
    import scandir
ModuleNotFoundError: No module named 'scandir'

However, the dependency already exists:

Requirement already satisfied: scandir in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.10.0)
Requirement already satisfied: pefile in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2019.4.18)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (4.6.1)
Requirement already satisfied: future in /usr/local/lib/python3.8/site-packages (from pefile->-r requirements.txt (line 2)) (0.18.2)

Unsure how to proceed...

macOS Catalina
Version 10.15.7
MacBook Pro (16-inch, 2019)
Processor 2.6 GHz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4
Graphics AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB

**Comment by galitz** [comment]
Hi.. did you verify you are calling yarGen with the correct python version?  I just ran into this same issue when my system was configured to use python2 by default instead of python3, though I had assumed otherwise.

**Comment by archanchoudhury** [comment]
Hi, So you will get the same error even after you try to call yarGen.py using Python3. The requirement installation won't give you anything though.

So solution is, run 
python3 -m pip install scandir lxml naiveBayesClassifier pefile

and then Run the update using python3 yarGen.py --update

Defo, you have downloaded the current version of the yarGen from Git, which is using Python3 by default.
