### ISSUE TITLE
[question] [E] Missing goodware imphash/export databases. Error question

### ISSUE THREAD

**Issue by hellokmk** [Neo23x0/yarGen#32]
I tried to create the yargen_rules.yar rule, but the following error message occurred. 
All db files under the ./dbs/ directory exist normally, but an error occurs during execution. May I inquire about any problems?

========================================================================================

[...]# /root/hacking/yarGen-0.21.2/yarGen.py -m /root/hacking/hackfile/
###############################################################################
                        ______
      __  ______ ______/ ____/__  ____
     / / / / __ `/ ___/ / __/ _ \/ __ \
    / /_/ / /_/ / /  / /_/ /  __/ / / /
    \__, /\__,_/_/   \____/\___/_/ /_/
   /____/
 
   Yara Rule Generator by Florian Roth
   December 2018
   Version 0.21.1
 
###############################################################################
[+] Using identifier 'hacking'
[+] Using reference 'https://github.com/Neo23x0/yarGen'
[+] Using prefix 'hacking'
[+] Processing PEStudio strings ...
[+] Reading goodware strings from database 'good-strings.db' ...
    (This could take some time and uses at least 3 GB of RAM)
[+] Loading ./dbs/good-exports-part1.db ...
Traceback (most recent call last):
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 2407, in <module>
    good_exports_pickle = load(get_abs_path(filePath))
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 1912, in load
    object = pickle.loads(buffer)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '{'
[+] Loading ./dbs/good-imphashes-part8.db ...
Traceback (most recent call last):
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 2396, in <module>
    good_imphashes_pickle = load(get_abs_path(filePath))
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 1912, in load
    object = pickle.loads(buffer)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '{'
[+] Loading ./dbs/good-imphashes-part3.db ...
Traceback (most recent call last):
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 2396, in <module>
    good_imphashes_pickle = load(get_abs_path(filePath))
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 1912, in load
    object = pickle.loads(buffer)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '{'
[+] Loading ./dbs/good-imphashes-part4.db ...
Traceback (most recent call last):
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 2396, in <module>
    good_imphashes_pickle = load(get_abs_path(filePath))
  File "/root/hacking/yarGen-0.21.2/yarGen.py", line 1912, in load
    object = pickle.loads(buffer)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '{'
...
...
[+] Loading ./dbs/good-exports-part9.db ...
Traceback (most recent call last):
  File "yarGen.py_0.21.1", line 2407, in <module>
    good_exports_pickle = load(get_abs_path(filePath))
  File "yarGen.py_0.21.1", line 1912, in load
    object = pickle.loads(buffer)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '{'
[E] Missing goodware imphash/export databases.     Please run 'yarGen.py --update' to retrieve the newest database set.
[E] Error - no goodware databases found.     Please run 'yarGen.py --update' to retrieve the newest database set.

[... yarGen-0.21.2]# ll ./dbs/good-imphashes-part6.db
-rw-r--r--. 1 root root 715 Dec 15 01:15 ./dbs/good-imphashes-part6.db
[... yarGen-0.21.2]# ll ./dbs/good-exports-part9.db
-rw-r--r--. 1 root root 44 Dec 15 01:08 ./dbs/good-exports-part9.db
 
 
[... dbs]# pwd
/root/hacking/yarGen-0.21.2/dbs

[... dbs]# ll
total 785860
-rw-r--r--. 1 root root   1555146 Dec 15 00:35 good-exports-part1.db
-rw-r--r--. 1 root root   1238335 Dec 15 00:35 good-exports-part2.db
-rw-r--r--. 1 root root   1656390 Dec 15 00:35 good-exports-part3.db
-rw-r--r--. 1 root root   1234219 Dec 15 01:23 good-exports-part4.db
-rw-r--r--. 1 root root   2570093 Dec 15 01:16 good-exports-part5.db
-rw-r--r--. 1 root root     74998 Dec 15 00:55 good-exports-part6.db
-rw-r--r--. 1 root root   1441009 Dec 15 00:37 good-exports-part7.db
-rw-r--r--. 1 root root    151144 Dec 15 00:35 good-exports-part8.db
-rw-r--r--. 1 root root        44 Dec 15 01:08 good-exports-part9.db
-rw-r--r--. 1 root root     32275 Dec 15 00:35 good-imphashes-part1.db
-rw-r--r--. 1 root root     21598 Dec 15 01:29 good-imphashes-part2.db
-rw-r--r--. 1 root root     81395 Dec 15 01:16 good-imphashes-part3.db
-rw-r--r--. 1 root root     51426 Dec 15 01:08 good-imphashes-part4.db
-rw-r--r--. 1 root root    148364 Dec 15 00:35 good-imphashes-part5.db
-rw-r--r--. 1 root root       715 Dec 15 01:15 good-imphashes-part6.db
-rw-r--r--. 1 root root     72273 Dec 15 01:08 good-imphashes-part7.db
-rw-r--r--. 1 root root      3906 Dec 15 00:35 good-imphashes-part8.db
-rw-r--r--. 1 root root        52 Dec 15 01:01 good-imphashes-part9.db
-rw-r--r--. 1 root root  40036608 Dec 15 01:23 good-opcodes-part1.db
-rw-r--r--. 1 root root  37660735 Dec 15 00:39 good-opcodes-part2.db
-rw-r--r--. 1 root root  86709267 Dec 15 01:08 good-opcodes-part3.db
-rw-r--r--. 1 root root  36161350 Dec 15 01:20 good-opcodes-part4.db
-rw-r--r--. 1 root root 236825132 Dec 15 00:55 good-opcodes-part5.db
-rw-r--r--. 1 root root  19250880 Dec 15 00:37 good-opcodes-part6.db
-rw-r--r--. 1 root root  75104057 Dec 15 01:15 good-opcodes-part7.db
-rw-r--r--. 1 root root   7902850 Dec 15 01:02 good-opcodes-part8.db
-rw-r--r--. 1 root root        44 Dec 15 01:29 good-opcodes-part9.db
-rw-r--r--. 1 root root  24735115 Dec 15 00:57 good-strings-part1.db
-rw-r--r--. 1 root root  27676540 Dec 15 01:25 good-strings-part2.db
-rw-r--r--. 1 root root  57603741 Dec 15 01:29 good-strings-part3.db
-rw-r--r--. 1 root root  39814980 Dec 15 01:11 good-strings-part4.db
-rw-r--r--. 1 root root  67488946 Dec 15 01:01 good-strings-part5.db
-rw-r--r--. 1 root root   7909572 Dec 15 01:02 good-strings-part6.db
-rw-r--r--. 1 root root  24281798 Dec 15 00:35 good-strings-part7.db
-rw-r--r--. 1 root root   5137210 Dec 15 00:36 good-strings-part8.db
-rw-r--r--. 1 root root     14745 Dec 15 01:15 good-strings-part9.db

**Comment by Neo23x0** [comment]
You're using an old version of yarGen (which still uses pickle) with the new databases (JSON).

**Comment by hellokmk** [comment]
Thank you! After installing the python3 version, I checked the normal execution.
