### ISSUE TITLE
Dropzone: specific filename for every YARA rule

### ISSUE THREAD

**Issue by sustefil** [Neo23x0/yarGen#35]
Hi there!

I am new to yarGen, sorry for potentially noobish question.

Is there a possibility to specify different output file for YARA rule for each file?

I am trying to built an automated YARA rule creation with dropzone (files dropping there randomly), but the file `yargen_rules.yar` is being overwritten after a file is processed.

Or is it just designed to drop one file at a time and collect the rule? I could then build some queueing around it.

Thanks in advance.

**Comment by sustefil** [comment]
And additional question:  Does the dropzone support super-rules for multiple files?

**Comment by Neo23x0** [comment]
> Is there a possibility to specify different output file for YARA rule for each file?

No. 

> And additional question: Does the dropzone support super-rules for multiple files?

It should work like the normal generation run, so, yes.
