### ISSUE TITLE
the issue with -m args < 2

### ISSUE THREAD

**Issue by resteex0** [Neo23x0/yarGen#37]
the issue with -m args < 2 not read path file

**Comment by Neo23x0** [comment]
I don't understand the question / problem

**Comment by resteex0** [comment]
Am sorry ,and thanx for your effort 
 my problem solved , should systex same as
Python3 yarGen.py -m /folder/ - o /path/file.yar

**Comment by resteex0** [comment]
> I don't understand the question / problem
can mdifed the "Using identifier 'test'" = issue identifier take folder only , this making issue every time please edit to take every file or folder not folder only ,

same as 
Python3 yarGen.py -m /folder/test.exe - o /path/file.yar

the yarGen identifier should take anything not folder only
