### ISSUE TITLE
0 rules being generated

### ISSUE THREAD

**Issue by seanthegeek** [Neo23x0/yarGen#4]
When I use the latest commit (03112619477e47f3d337f4e827f1c2b90ccb2f8c) 0 simple or super rules are being generated.

$ python yarGen.py -a "Sean Whalen" -m /opt/malware/droppers/upatre -o upatre.yar
###### 

```
                    ______
  __  ______ ______/ ____/__  ____
 / / / / __ `/ ___/ / __/ _ \/ __ \
/ /_/ / /_/ / /  / /_/ /  __/ / / /
\__, /\__,_/_/   \____/\___/_/ /_/
```

   /____/

   Yara Rule Generator
   by Florian Roth
   July 2015
   Version 0.15.0 beta
###### 

[+] Processing PEStudio strings ...
[+] Reading goodware strings from database 'good-strings.db' and 'good-opcodes.db' ...
    (This could take some time and uses up to 4 GB of RAM)
[+] Initializing Bayes Filter ...
[-] Training filter with good strings from ./lib/good.txt
[+] Processing malware files ...
[+] Processing /opt/malware/droppers/upatre/app_details.exe ...
[-] Extracting Strings: /opt/malware/droppers/upatre/app_details.exe
[-] Extracting OpCodes: /opt/malware/droppers/upatre/app_details.exe
[+] Processing /opt/malware/droppers/upatre/application_features.exe  ...
[-] Extracting Strings: /opt/malware/droppers/upatre/application_features.exe
[-] Extracting OpCodes: /opt/malware/droppers/upatre/application_features.exe
[-] Skipping strings/opcodes from /opt/malware/droppers/upatre/application_features.exe  due to MD5 duplicate detection
[+] Processing /opt/malware/droppers/upatre/application_information.exe ...
[-] Extracting Strings: /opt/malware/droppers/upatre/application_information.exe
[-] Extracting OpCodes: /opt/malware/droppers/upatre/application_information.exe
[-] Skipping strings/opcodes from /opt/malware/droppers/upatre/application_information.exe due to MD5 duplicate detection
[+] Processing /opt/malware/droppers/upatre/cadvahin.exe ...
[-] Extracting Strings: /opt/malware/droppers/upatre/cadvahin.exe
[-] Extracting OpCodes: /opt/malware/droppers/upatre/cadvahin.exe
[+] Processing /opt/malware/droppers/upatre/Transfer_blocked.exe ...
[-] Extracting Strings: /opt/malware/droppers/upatre/Transfer_blocked.exe
[-] Extracting OpCodes: /opt/malware/droppers/upatre/Transfer_blocked.exe
[+] Generating statistical data ...
[+] Generating Super Rules ... (a lot of foo magic)
[+] Generating simple rules ...
[-] Applying intelligent filters to string findings ...
[+] Generating super rules ...
[=] Generated 0 SIMPLE rules.
[=] Generated 0 SUPER rules.
[=] All rules written to upatre.yar
sean@sandbox:~/yarGen$ cat upatre.yar
/*
        Yara Rule Set
        Author: Sean Whalen
        Date: 2015-08-12
        Identifier: upatre
*/

/\* Global Rule -------------------------------------------------------------- _/
/_ Will be evaluated first, speeds up scanning process, remove at will */

global private rule gen_characteristics {
        condition:
                uint16(0) == 0x0000 and filesize < 201KB
}

/\* Rule Set ----------------------------------------------------------------- */

/\* Super Rules ------------------------------------------------------------- */

**Comment by Neo23x0** [comment]
Please check the actual content of app_details.exe 

It generates a "uint16(0) == 0x0000", which means that the first two bytes of the file are 00 and 00. This is very uncommon. (AV cleanup, empty file, read access error?)

Could you provide a MD5 hash of the sample?

**Comment by seanthegeek** [comment]
I can read the file as the same user I rasn yarGen with

837784962a9f5fecc3df21b6e0507860  /opt/malware/droppers/upatre/app_details.exe

**Comment by Neo23x0** [comment]
The file seems to be a valid file from the Microsoft software catalogue.
https://www.virustotal.com/en/file/1fe3b06aac001b1c5abba8650f760bc3347e8d0e5c64b197d6fa2ac1d09b8803/analysis/

So - all extracted strings and all extracted opcodes are unusable. 

Or did you try to create an "inverse matching" rule?

**Comment by seanthegeek** [comment]
I did some checking, and It looks like my entire malware collection got corrupted when I copied it to a new server. Sorry.
