### ISSUE TITLE
db files recognition issues

### ISSUE THREAD

**Issue by ayebachchu** [Neo23x0/yarGen#5]
![1](https://cloud.githubusercontent.com/assets/15387307/10852874/7ff6cbfe-7f76-11e5-8a69-9ab554fa32d2.PNG)
![2](https://cloud.githubusercontent.com/assets/15387307/10852875/801b8516-7f76-11e5-8e11-54a94a73ff4e.PNG)
I unziped good_opcodes.db.zip and good-strings.db in yarGen-master folder.
But yarGen.py can't recognize db files like picture.
Please help

**Comment by Neo23x0** [comment]
yarGen looks for those files in the current working directory. 
Change directory to the program directory first and then run the tool.

cd "C:\Documents and Settings\Administrator\"
python yarGen.py --help

**Comment by ayebachchu** [comment]
thank you for rapid feedback.
![3](https://cloud.githubusercontent.com/assets/15387307/10854242/d3a8cd5e-7f7d-11e5-899a-2e89da025a1c.PNG)
I can use 5.89GB of RAM but when I use yarGen, problem occured like picture above.
May I have answer?

**Comment by Neo23x0** [comment]
Use --noop parameter to save memory.

**Comment by ayebachchu** [comment]
![4](https://cloud.githubusercontent.com/assets/15387307/10857771/5c74259c-7f93-11e5-9263-151f6e61889f.PNG)
ok... I have test with python2.7(64bit) and --noop parameter. but no reaction..

**Comment by ayebachchu** [comment]
oh, i know. I have to give options. but I got a TypeError.
![5](https://cloud.githubusercontent.com/assets/15387307/10858955/3340e206-7f9c-11e5-920d-1f46bea77eb2.PNG)

and so slow to proceed.
How many memories I should have to process rapidly?

**Comment by Neo23x0** [comment]
Don't use a malware path with unicode characters.
Use ASCII path only e.g. C:\malware\sample1

And - please read the readme.
You'll get an idea what it does and why processing takes a long time.
Use --noop. You didn't use it in your screenshot.

On Fri, Oct 30, 2015 at 10:55 PM, ayebachchu notifications@github.com
wrote:

> oh, i know. I have to give options. but I got a TypeError.
> [image: 5]
> https://cloud.githubusercontent.com/assets/15387307/10858955/3340e206-7f9c-11e5-920d-1f46bea77eb2.PNG
> 
> and so slow to proceed.
> How many memories I should have to process rapidly?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Neo23x0/yarGen/issues/5#issuecomment-152659830.

## 

Sincerely
Saludos cordiales
Mit freundlichen Grüßen
Florian Roth

PGP Key:
https://www.dropbox.com/sh/lw9ymama8rjukjs/zNQZAujnQM
Key ID:
FE04247D50D1ACC855CB FD26 19E9 BF9E 78C1  D582 FE04 247D 50D1 ACC8

**Comment by seifreed** [comment]
The issue stills open?
