### ISSUE TITLE
running on linux

### ISSUE THREAD

**Issue by simonk9** [Neo23x0/yarGen#6]
Hi Florian,

I gave yarGen a try on my Ubuntu, it worked well, but i have two things to address:

1) In your installation guide in the read-me you suggest installing pickle, in my case it couldn’t find such package, but yarGen worked without it.

2) i got a nice warning message suggesting i should download PEStudio to improve speed, but there is no PEStudio for Linux yet, suggestions?

**Comment by Neo23x0** [comment]
Hi Simon, 

1) Pickle was the old database format. I'll remove this from the guide. 
2) PEStudio is not needed. All you need is the strings.xml from the program package. Place this file in the yarGen program folder. 

Cheers,

**Comment by simonk9** [comment]
thank you, i thought of doing so, but than i thought if it is that simple, why not just include it builtin in your repo?

**Comment by Neo23x0** [comment]
Because Mark asked me to include a link instead of the XML files:
1.) all lot of effort went into the XML and just including it would be "unfair"
2.) it would generate more attention for his great work

**Comment by simonk9** [comment]
confirmed, adding that file remove the warning message, haven’t tested for speed improvement, i'm sure you already did :)

I never meant to disrespect Mark's work, and when i said to include that  file, that would also include credits to him in the readme and the code.

if you want to generate even more attention to his work, you can add that step to the installation guide in the readme.

p.s. greetings from the local enlightened
