### ISSUE TITLE
possible problem when no permission to read files

### ISSUE THREAD

**Issue by simonk9** [Neo23x0/yarGen#7]
@Neo23x0 Hi, think i have found some real issue(s) this time.

1) Tried to create super rule for 15 similar executables (at least the strings does) and it created only 6.
i looked at the log and saw 9 lines like this:

[+] Processing /home/remnux/Desktop/winexec/cafb416560f61a7812917638fd6b0657403c10a5bfdcb8d9d2e26db89b3040e0.bin ...
[-] Skipping strings/opcodes from /home/remnux/Desktop/winexec/cafb416560f61a7812917638fd6b0657403c10a5bfdcb8d9d2e26db89b3040e0.bin due to MD5 duplicate detection
[+] Processing /home/remnux/Desktop/winexec/4df547b75a382539fa41c711d6f4b11f144267f9715ae3e0dda43e0b51623326.bin ...
[-] Skipping strings/opcodes from /home/remnux/Desktop/winexec/4df547b75a382539fa41c711d6f4b11f144267f9715ae3e0dda43e0b51623326.bin due to MD5 duplicate detection

i noticed the file date is funny on those 9 files that were skipped, and since they were extracted from zip, i decided to try to change their permissions.
ran again, and it worked:

[+] Processing /home/remnux/Desktop/winexec/cafb416560f61a7812917638fd6b0657403c10a5bfdcb8d9d2e26db89b3040e0.bin ...
[-] Extracting Strings: /home/remnux/Desktop/winexec/cafb416560f61a7812917638fd6b0657403c10a5bfdcb8d9d2e26db89b3040e0.bin
148 ASCII strings extracted
1 ASCII strings extracted
[+] Processed /home/remnux/Desktop/winexec/cafb416560f61a7812917638fd6b0657403c10a5bfdcb8d9d2e26db89b3040e0.bin Size: 19456 Strings: 222 OpCodes: 0 ... 

so it looks like it skips the files for the wrong reason.

2) im not good at math, but the numbers on the output above doesn’t seem to match, could be wrong print, or an issue, or just not enough detailed debug info (why the 2nd print of 1 ascii string?)

3) im quite sure this is intended, but my output didn’t had a super rule, although all the 15 files
had a full match on 1 particular substring they all shared, although the full strings varied.
for example:

file1:
$s1 = aabrakadabra
$s2 = aaa

file2:
$s1 = babrakadabra
$s2 = bbb

file3:
$s1 = cabrakadabra
$s2 = ccc

so the full strings dont match at all.

but a super rule with:

$s1 = abrakadabra

would catch them all.

again, not sure if this intended or not, if not, might be a very nice improvement.

**Comment by seifreed** [comment]
Hi @simonk9 this issue stills persists?

**Comment by simonk9** [comment]
@seifreed unfortunately i dont use Yara now days so i cant tell, but since @Neo23x0 haven't responded, there is a chance the issues still exist.
